name: Continuous deployment (rc)

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/telstrapurple/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
    - name: Build
      run: dotnet build --configuration Release -p:VersionPrefix=${{steps.gitversion.outputs.MajorMinorPatch}}-rc${{steps.gitversion.outputs.CommitsSinceVersionSourcePadded}}
    - name: Publish the package to Github packages
      run: dotnet nuget push Banjo.CLI/Banjo.CLI.${{steps.gitversion.outputs.MajorMinorPatch}}-rc${{steps.gitversion.outputs.CommitsSinceVersionSourcePadded}}.nupkg
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: banjo-cli-${{steps.gitversion.outputs.MajorMinorPatch}}-rc${{steps.gitversion.outputs.CommitsSinceVersionSourcePadded}}
        path: '**/*.nupkg'
